### ISSUE TITLE
TypeORM thwors “Type instantiation is excessively deep and possibly infinite.ts(2589)” error on Repository typing

### ISSUE THREAD

**Issue by daniel-dia** [typeorm/typeorm#4696]
After update to [VSCode August 2019 (version 1.38) and Typescript 3.6][1] i'm getting a lot of the fallowing error on a [TypeORM][2] repository initialization.

> Type instantiation is excessively deep and possibly infinite.ts(2589) 

There also is the fallowing error on the file.

> Excessive stack depth comparing types 'FindConditions<?>' and 'FindConditions<?>'

``` typescript
import { Connection, Repository, Entity, BaseEntity,  createConnection } from 'typeorm';
    
@Entity()
class MyEntity extends BaseEntity {
    public id: number;
}
    
class Test {
    async test() {
        const connection: Connection = await createConnection();
        const myRepo: Repository<MyEntity> = connection.getRepository(MyEntity); 
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    }
}

```
   
How can I ignore or fix them?

 - VSCode `v1.38.0 (user setup)`
 - Node.js `v10.11.0`
 - Typescript `v3.4.5`
 - TypeORM `v0.2.18`

I also noticed that the error is gone if the typing is removed `: Repository<MyEntity>`

  [1]: https://code.visualstudio.com/updates/v1_38#_typescript-36
  [2]: https://typeorm.io/

**Comment by gsoare2** [comment]
![image](https://user-images.githubusercontent.com/23703101/64344135-3cacad80-cfc4-11e9-8129-8d6e6c11127f.png)

Me too.

**Comment by sergey-telpuk** [comment]
I also have such errors
```ts
> nest-typescript-starter@1.0.0 build /app
> tsc -p tsconfig.build.json

error TS2321: Excessive stack depth comparing types 'FindConditions<?>' and 'FindConditions<?>'.

error TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'.

node_modules/typeorm/repository/MongoRepository.d.ts:12:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

12 export declare class MongoRepository<Entity extends ObjectLiteral> extends Repository<Entity> {
                        ~~~~~~~~~~~~~~~

node_modules/typeorm/repository/MongoRepository.d.ts:45:5 - error TS2321: Excessive stack depth comparing types '(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>) => Promise<Entity>' and '{ (id?: string | number | Date | ObjectID, options?: FindOneOptions<Entity>): Promise<Entity>; (options?: FindOneOptions<Entity>): Promise<Entity>; (conditions?: FindConditions<Entity>, options?: FindOneOptions<...>): Promise<...>; }'.

45     findOne(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>): Promise<Entity | undefined>;

```

**Comment by oscar-corredor** [comment]
Same here
![image](https://user-images.githubusercontent.com/1540961/64444657-41439580-d09a-11e9-9ad2-51158319d849.png)

**Comment by yarrumretep** [comment]
This issue happens with the Typescript example: https://github.com/typeorm/typescript-example

Clone that repo, then `yarn && yarn start`

**Comment by vytautas-pranskunas-** [comment]
any updates on this?

**Comment by ichn-hu** [comment]
I have encountered the same error!

**Comment by seandearnaley** [comment]
+1

**Comment by seandearnaley** [comment]
fixed on my build using "typescript": "^3.6.3-insiders.20190909" in package.json, presume 3.6.3 is imminent

**Comment by wallopthecat** [comment]
Roll back to 3.5.3 fixed something similar for me until 3.6.3 drops

**Comment by Mikkal24** [comment]
Are we sure this is a TypeORM issue? I just updated mine from 0.2.18 to 0.2.19 and the error went away. Feels like VScode's intellisense is being finnicky.

**Comment by daniel-dia** [comment]
This can be solved it by using a previous version of Typescript.

First be sure that the typescript version on your workspace "npm" is lower than `3.6`. For instance:  `package.json`:

    "dependencies": {
        ...
        "typescript": "^3.0.3"
    }


If your workspace have `3.6.x` or greater, install a previous version typing `npm install typescript@3.4.3`





Then, **with a `.ts` file opened**, a typescript version selector will appear on status bar. (version `^3.6.x` probably being displayed)



[![enter image description here][1]][1]

then choose **"Use Workspace Version"** instead of **"VS Code's Version"**


[![enter image description here][2]][2]

Be sure that workspace version is also lower than `3.6.x` ex here version `3.4.3` is on my workspace. Or else force install a previous version as previouly mentioned



[![enter image description here][3]][3]



Now that version `^3.4.x` is selected, you should not have this kind of error on VS Code nor `tsc` commands.



Note: Since workspace Typescript version is compatible with TypeORM, running scripts like `npm run build` should not throw any errors cause it will use Typescript workspace binaries. The errors will only occurs on VS Code or direct `tsc` commands on terminal


  [1]: https://i.stack.imgur.com/jHF3H.png
  [2]: https://i.stack.imgur.com/8o39u.png
  [3]: https://i.stack.imgur.com/OhddO.png

**Comment by imnotjames** [comment]
Cannot replicate.  Seems to be a typescript bug.

**Comment by Pavel-Husakouski** [comment]
I reproduced the issue: 
ts 5.7.2
typeorm 0.3.20
`
export type Json = string | number | boolean | null | JsonArray | JsonObject;
export type JsonObject = { [key: string]: Json };


  @Column({ type: 'jsonb', array: false, nullable: false })
  payload: JsonObject;
`
The fix is either to use the dedicated type instead of JsonObject, or to explicitly cast the object to QueryDeepPartialEntity
