### ISSUE TITLE
Typescript error: TS2611: 'queryRunner' is defined as a property in class 'EntityManager', but is overridden here in 'MongoEntityManager' as an accessor.

### ISSUE THREAD

**Issue by mschnee** [typeorm/typeorm#6806]
Projects using `typeorm@0.2.27` fail to build due to an error:
```
node_modules/typeorm/entity-manager/MongoEntityManager.d.ts:27:9 - error TS2611: 'queryRunner' is defined as a property in class 'EntityManager', but is overridden here in 'MongoEntityManager' as an accessor.

27     get queryRunner(): MongoQueryRunner;
           ~~~~~~~~~~~

```
This is fixed my reverting to `0.2.26`

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**TypeScript version** `v4.0.3`

**Comment by imnotjames** [comment]
We aren't using typescript 4.0 yet - does it work with typescript 3.9?

**Comment by wy193777** [comment]
I tested 0.2.27 on typescript 3.9 and it works for me.

**Comment by imnotjames** [comment]
That's a bummer.  Is there a configuration option we can be using to prevent that?  Or is it just a limitation that's imposed in 4.0 that's not in 3.9?

Is 4.0 backwards compatible?

**Comment by imnotjames** [comment]
I think this is a duplicate of #6805

**Comment by imnotjames** [comment]
I'll be closing this issue in favor of #6805

Cheers
