### ISSUE TITLE
SQLLite synchronize error

### ISSUE THREAD

**Issue by bpatrik** [typeorm/typeorm#1365]
Hi,

I think I found a bug in the latest (v 0.1.9) version of typeorm.
I'm using sqlite. 
I do the following:
1) I open a connection
2) save a some entities:
```typescript
let dir0={...}

let dir1 ={
   parent:dir0
}
let photo={
   directory:dir1
}
```
3) close the connection and reopen it.

I got the following errors:
1) typeorm think that the scheme was changed (but was not)
2) It tries to recreate the tables but because of the foreign key constraint, it can not
```
primary keys of directory_entity has changed: dropped - nothing; added - id
executing query:  CREATE TABLE "temporary_directory_entity" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar NOT NULL, "path" varchar NOT NULL, "lastModified" bigint NOT NULL, "lastScanned" bigint, "parentId" integer, FOREIGN KEY("parentId") REFERENCES "directory_entity"("id"))
executing query:  INSERT INTO "temporary_directory_entity"("id", "name", "path", "lastModified", "lastScanned", "parentId") SELECT "id", "name", "path", "lastModified", "lastScanned", "parentId" FROM "directory_entity"
executing query:  DROP TABLE "directory_entity"
query failed:  DROP TABLE "directory_entity"
error:  { Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
    at Error (native) errno: 19, code: 'SQLITE_CONSTRAINT' }
executing query:  ROLLBACK
```

see detailed error here:
https://travis-ci.org/bpatrik/pigallery2/jobs/318708916
code that can reproduce the error:
https://github.com/bpatrik/pigallery2/blob/develop/test/backend/integration/model/sql/typeorm.ts
(see test case: `should open and close connection twice  with photo added`)

Thank you dor your help!
Patrik

**Comment by renanfferreira** [comment]
Same problem here

**Comment by aluco100** [comment]
Same problem

**Comment by renanfferreira** [comment]
I found this comment at the property

/*
     * Indicates if database schema should be auto created on every application launch.
     * **Be careful with this option and don't use** this in production - otherwise you can loose production data.
     * This option is useful during debug and development.
     * Alternative to it, you can use CLI and run schema:sync command.
     *
     * Note that for MongoDB database it does not create schema, because MongoDB is schemaless.
     * Instead, it syncs just by creating indices.
     */

Now I'm not using this option, instead, I use the code bellow to sync my database.

await con.dropDatabase();
await con.synchronize();

All data is provided by backend, so I can drop my DB and sync again with fresh data.

**Comment by pleerock** [comment]
> Now I'm not using this option, instead, I use the code bellow to sync my database.
await con.dropDatabase();
await con.synchronize();

Result is the same - `synchronize` uses con.synchronize to sync data, this note in the comment just to let you know that you should syncrhonize your schema carefully each time when you are doing it in a production with exist data.

**Comment by bpatrik** [comment]
My problem is rather that the typeorm wanted to synchronize even if there was no change in the scheme and It failed doing the sync.

**Comment by AlexMesser** [comment]
@bpatrik please check this issue on `@next` version

**Comment by AlexMesser** [comment]
I will close it for now, please let me know if its not fixed in latest `next` version

**Comment by radu2323** [comment]
This error is still happening. Tested with "typeorm": "0.2.24", "sql.js": "1.2.2". I've tried both with synchronize set to false and connection.synchronize. It doesn't matter what I do. It crashes with query failed:  DROP TABLE (TypeError: qa is not a function).

**Comment by jordanorc** [comment]
Same problem reported by @radu2323. It happens when I use a @ManyToOne relation. TypeORM tries to create a temp table:` INSERT INTO "temporary_author"`, and then the error occurs: `TypeError: qa is not a function`. I have an example project if needed. I'm also using "typeorm": "0.2.24" and "sql.js": "1.2.2"

**Comment by jordanorc** [comment]
@radu2323, just an update. I try to downgrade sql.js to version 1.1.0 and it works!!! When updating it to 1.2.1 or 1.2.2, the problem appears. There is any incompatibility between the latest version of TypeORM and sql.js?

**Comment by radu2323** [comment]
Good to know, I used version 0.5.0

**Comment by schuerg** [comment]
I encounter the same problem with `sql.js 1.2.2` and `typeorm 0.2.24`.

An autogenerated migration from TypeORM cannot be performed:
```
query:  BEGIN TRANSACTION
query:  CREATE TABLE "temporary_Person" ...
query:  DROP TABLE "Person"
query failed:  DROP TABLE "Person"
PlatformTools.js:105 error:  TypeError: qa is not a function
    at Iu (sql-asm.js:125)
    at Bu (sql-asm.js:113)
    at Gu (sql-asm.js:125)
    at Array.ks (sql-asm.js:101)
    at tb (sql-asm.js:101)
    at ql (sql-asm.js:101)
    at im (sql-asm.js:97)
    at Va (sql-asm.js:101)
    at e._sqlite3_step (sql-asm.js:214)
    at a.step (sql-asm.js:78)
```

**Comment by bolivir** [comment]
> I encounter the same problem with `sql.js 1.2.2` and `typeorm 0.2.24`.
> 
> An autogenerated migration from TypeORM cannot be performed:
> 
> ```
> query:  BEGIN TRANSACTION
> query:  CREATE TABLE "temporary_Person" ...
> query:  DROP TABLE "Person"
> query failed:  DROP TABLE "Person"
> PlatformTools.js:105 error:  TypeError: qa is not a function
>     at Iu (sql-asm.js:125)
>     at Bu (sql-asm.js:113)
>     at Gu (sql-asm.js:125)
>     at Array.ks (sql-asm.js:101)
>     at tb (sql-asm.js:101)
>     at ql (sql-asm.js:101)
>     at im (sql-asm.js:97)
>     at Va (sql-asm.js:101)
>     at e._sqlite3_step (sql-asm.js:214)
>     at a.step (sql-asm.js:78)
> ```

Did you find any solution for the problem?
