### ISSUE TITLE
Excessive stack depth comparing types 'FindConditions<?>' and 'FindConditions<?>' (with solution)

### ISSUE THREAD

**Issue by mophy** [typeorm/typeorm#4427]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Compile any code that will use the `FindConditions` type, and the error occurs:

`error TS2321: Excessive stack depth comparing types 'FindConditions<?>' and 'FindConditions<?>'.`

TypeScript versions which will trigger this error: 3.2.4, 3.5.3
TypeScript versions which will NOT trigger this error: <=3.1.6

According to [this link](https://github.com/microsoft/TypeScript/issues/21592#issuecomment-496723647), this can be fixed, just modify the `FindConditions.d.ts` file from

```
export declare type FindConditions<T> = {
    [P in keyof T]?: FindConditions<T[P]> | FindOperator<FindConditions<T[P]>>;
};
```

to

```
export declare type FindConditions<T> = {
    [P in keyof T]?: T[P] extends never ? FindConditions<T[P]> | FindOperator<FindConditions<T[P]>> : FindConditions<T[P]> | FindOperator<FindConditions<T[P]>>;
};
```

After this change, TypeScript 3.2.4 and 3.5.3 will not trigger that error, and TypeScript 3.1.6 works well too.

I can submit a PR if needed.

**Comment by Aibokalv** [comment]
i  fix this problem by  run `npm install typescript@3.6.2 --save -g`

**Comment by jraoult** [comment]
@mophy thx for the suggestion. I'm not the repo maintainer but I think you should create a PR. It's an easy one to merge and hopefully, we can get someone to accept it quickly 😄

**Comment by haydennyyy** [comment]
I've got this issue with `MongoRepository#findOne`

**Comment by haydennyyy** [comment]
```
error TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'.

node_modules/typeorm/repository/MongoRepository.d.ts:12:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

12 export declare class MongoRepository<Entity extends ObjectLiteral> extends Repository<Entity> {
                        ~~~~~~~~~~~~~~~

node_modules/typeorm/repository/MongoRepository.d.ts:45:5 - error TS2321: Excessive stack depth comparing types '(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>) => Promise<Entity>' and '{ (id?: string | number | Date | ObjectID, options?: FindOneOptions<Entity>): Promise<Entity>; (options?: FindOneOptions<Entity>): Promise<Entity>; (conditions?: FindConditions<Entity>, options?: FindOneOptions<...>): Promise<...>; }'.

45     findOne(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>): Promise<Entity | undefined>;
       ~~~~~~~
```

**Comment by mophy** [comment]
@jraoult, PR is here: https://github.com/typeorm/typeorm/pull/4470

**Comment by mophy** [comment]
@haydennyyy, there's a workaround in PR https://github.com/typeorm/typeorm/pull/4470

**Comment by keawade** [comment]
This is probably related to this issue in Typescript: https://github.com/microsoft/TypeScript/issues/21592

**Comment by risa** [comment]
It seems that a Typescript fix is coming, I can confirm that it works with the 3.7.0-insiders.20190902 version.
See here: https://github.com/microsoft/TypeScript/pull/33144#issuecomment-527237940

**Comment by Majidahmadi** [comment]
In compile by typescript 3.6.2 , this problem is encountered, but there is no problem in 3.4.5 version!

**Comment by Kononnable** [comment]
Looks like issue was resolved some time ago.

**Comment by gbar** [comment]
Hi guys,
this fix
```
export declare type FindConditions<T> = {
    [P in keyof T]?: T[P] extends never ? FindConditions<T[P]> | FindOperator<FindConditions<T[P]>> : FindConditions<T[P]> | FindOperator<FindConditions<T[P]>>;
};
```

is causing
```
No overload matches this call.
  Overload 1 of 3, '(id?: string | number | Date | ObjectID, options?: FindOneOptions<T>): Promise<T>', gave the following error.
    Argument of type '{ hash: string; }' is not assignable to parameter of type 'string | number | Date | ObjectID'.
      Object literal may only specify known properties, and 'hash' does not exist in type 'Date | ObjectID'.
  Overload 2 of 3, '(conditions?: FindConditions<T>, options?: FindOneOptions<T>): Promise<T>', gave the following error.
    Argument of type '{ property: type; }' is not assignable to parameter of type 'FindConditions<T>'.
```

**Comment by greenreign** [comment]
@gbar did you ever figure out a solution?  I'm running into the same issue in 0.2.36

**Comment by eliaspn** [comment]
in my case going from 0.2.37 -> 0.2.45 fixed the issue
