### ISSUE TITLE
TypeScript 2.7.1 update cause repository.save(entity) error

### ISSUE THREAD

**Issue by rafaelbatistamarcilio** [typeorm/typeorm#1544]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When i update my typescript version to 2.7.1 my application's build broken with the follow error:

PS C:\dsv\nest-api> npm run start:prod
> nest-typescript-starter@1.0.0 prestart:prod C:\dsv\nest-api
> tsc

src/modules/common/services/base-data.service.ts(46,65): error TS2321: Excessive stack depth comparing types 'T' and 'DeepPartial<T>'.
src/modules/common/services/base-data.service.ts(67,65): error TS2345: Argument of type 'T' is not assignable to parameter of type 'DeepPartial<T>'.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nest-typescript-starter@1.0.0 prestart:prod: `tsc`
npm ERR! Exit status 2

The service code is the follow:

```
export abstract class BaseDataService<T extends BaseModel> implements ICrudService<T>{

    constructor() {

    }
   
    ... other crud methods   

    public abstract getRepository(): Repository<T>;
    
    public async save(entity: T): Promise<T> {
        try {
            const response: T = await this.getRepository().save(entity);
            return response;
        } catch (error) {
            throw new BadGatewayException('ERROR.BASEDATASERVICE.SAVE');
        }
   }

}
```

Someone know why this is happening?

Thanks!

**Comment by wiltonpolesca** [comment]
I've been having the same problem.
I'm using tsc version 2.4.2

**Comment by daniel-lang** [comment]
There is an issue open for that (Microsoft/TypeScript#21671). It seems like a regression issue on their part. Let's see what they have to say.

**Comment by pleerock** [comment]
@daniel-lang how to reproduce this? 

```ts
$ ./node_modules/.bin/tsc
$ ./node_modules/.bin/tsc -v
Version 2.7.1
```

I don't have such error checking on `typescript-example` with typeorm `0.1.12` installed.

**Comment by daniel-lang** [comment]
I'm unable to reproduce it now, but when I wrote the comment I was. That's very strange.

**Comment by pleerock** [comment]
@rafaelbatistamarcilio @adrianhara can you provide more information?

**Comment by xavism** [comment]
I'm stack too in this problem.. I'm using ts 2.7.2.

**Comment by pleerock** [comment]
anyone can tell how to reproduce this issue?

**Comment by xavism** [comment]
I can give you my repo if you want, there you have the version of each npm package.
I'm using NestJS with typeORM with a MySQL DB.

just:
npm i
npm start

You should change the typeormconfig to change the db

**Comment by pleerock** [comment]
yes it would be great

**Comment by xavism** [comment]
this is my repo:
Thx to check it out.

https://github.com/xavism/nestjs-crud

**Comment by pleerock** [comment]
@xavism thanks for the repo, but I expected something simple with a few lines of code, since example is complex Im not sure where is a problem.

Lets wait until #21671 is resolved by typescript team.

**Comment by xavism** [comment]
Sorry I thought would be easier to reproduce it.

Here I add a simple example

```typescript
export class BaseService<T extends BaseEntity> implements IBaseService<T>{
	constructor(
    private readonly genericRepository: Repository<T>) {
		console.log('Im the ORM Service');
	}

  create(entity: T): Promise<number>{
		return new Promise<number> ((resolve, reject) => {
			this.genericRepository.save(entity)
			.then(created=> resolve(created.id))
			.catch(err => reject(err))
			})
  }
}
```

**Comment by xavism** [comment]
The problem is generated in the save method, where you pass a parameter of type T

**Comment by aymehri** [comment]
I have the same error, any updates?

**Comment by daniel-lang** [comment]
@aymehri Microsoft/Typescript#21671 in favor of Microsoft/Typescript#21592 in which the Typescript Team acknowledged that it's a bug. The current target for a fix is TypeScript 2.8.1

**Comment by aymehri** [comment]
Thank you @daniel-lang , we just wait then. :)

**Comment by xavism** [comment]
@aymehri To use it before the fix in TS 2.8.1, you just have to pass the entity as any.

**Comment by pleerock** [comment]
I'll close it, let's track a typescript issue instead.

**Comment by pleerock** [comment]
Can you guys please check it in the `0.2.15-rc.1` ? (`npm i typeorm@0.2.15-rc.1`)

**Comment by rewieer** [comment]
Can confirm this work !

**Comment by pleerock** [comment]
Great! Would be great if everyone else confirm it

**Comment by EduardsE** [comment]
Downgrading to `0.2.15-rc.1` did not fix the issue for me.

**Comment by pisix** [comment]
me too

**Comment by EduardsE** [comment]
Although what did fix the issue was downgrading `typescript` to version `3.3.4000`

**Comment by lucianosantana** [comment]
Not for me, I was in 3.3.400. Downgrading to 3.1.6 did work, though. See : https://github.com/Microsoft/TypeScript/issues/29112#issuecomment-471341632
