### ISSUE TITLE
how to use the 'target' option on EntitySchemaOption on 0.2.2?

### ISSUE THREAD

**Issue by jkiyo** [typeorm/typeorm#2026]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to use the "target" option on my EntitySchema, but it does not working as I expected when I updated from 0.1.21 to 0.2.2

My schema configuration:
```
// UserSchema.js
const { EntitySchema } = require('typeorm')
const User = require('../entities/User')
                                                                                                                                                   
module.exports = new EntitySchema({
  name: 'User',
  target: User,
  tableName: 'user',
  columns: {
    id: {
      primary: true,
      type: 'int',
      generated: true
    },
    name: {
      name: 'name',
      type: 'varchar',
      nullable: false
    }
  } 
})
```

```
// User.js
class User {
  getNameWithFooAtEnd () { 
    return this.name + ' foo'
  } 
}
```

Test:
```
const { getConnection } = require('typeorm')
const repository = getConnection().getRepository('user')

...
const user = await repository.findOne(1)

console.log(user)
/*
User {
    id: 1,
    name: 'Bar' }
*/

console.log('instanceof?', user instanceof User) // false

console.log(user.getNameWithFooAtEnd())
// Throws "TypeError: user.getNameWithFooAtEnd is not a function"
```

Am I missing some config?

**Comment by pleerock** [comment]
I added corresponding tests and they are passing.

**Comment by jkiyo** [comment]
Yeah... your test case is working, Thanks @pleerock
Just updated to the latest version (0.2.4) and it started to work...
