### ISSUE TITLE
Why was the custom repository syntax changed?

### ISSUE THREAD

**Issue by nimloth05** [typeorm/typeorm#9013]
I'm currently migrating from 0.2 to 0.3 and noticed that the syntax for custom repository was changed. I personally find this change very odd but I assume typeorm devs have a perfectly fine explanation for this - I lack to find it though. Remark: I know that this issue is not a documentation issue per se but SO is not the place to discuss things that's why I decided to post it here.

Where I'm coming from: My project only uses a single relational database with various small custom repositories.

Here is a simple example repository from 0.2:

    import {User} from "../bl/user";
    import {EntityManager, EntityRepository, Repository} from "typeorm";
    
    @EntityRepository(User)
    export class UserRepository extends Repository<User> {
    
      findByEmail(email: string): Promise<User | undefined> {
        // Implementation not relevant
      }
    
      isEmailAlreadyInUser(email: string): Promise<boolean> {
          // Implementation not relevant
      }
    }
    
    export function getUserRepository(manager: EntityManager): UserRepository {
      return manager.getCustomRepository(UserRepository);
    }

New 0.3 version:

    // I have to manually create a type so UserRepository exists in type space.
    export type UserRepositoryType = Repository<User> & {
      findByEmail(email: string): Promise<User | null>;
      isEmailAlreadyInUser(email: string): Promise<boolean>;
    }
    
    // this UserRepository only exists in value space. Without my previous type declaration I cannot return it from my helper function.
    const UserRepository: UserRepositoryType = AppDataSource.getRepository(User).extend({
      findByEmail(email: string): Promise<User | null> {
        // Implementation not relevant
      },
    
      isEmailAlreadyInUser(email: string): Promise<boolean> {
        // Implementation not relevant
      }
    });
    
    // Helper function, so clients are shielded of typeoRM access.
    export function getUserRepository(manager: EntityManager): UserRepositoryType {
      return manager.withRepository(UserRepository);
    }

I'm wondering two things:

- Why was the class declaration style dropped? It seems much more "TS like" then the other. (Which seems more JS like but JS doesn't know about type space...)
- Why is the repo bound to a datasource? A repo - as I use it - is a concept from DDD in which case it encapsulates certain aspects of my business logic. Why should this logic change depending on the database I use?

As I sad before, this is not a critic since I'd like to understand the reasoning behind the change first.

**Comment by nimloth05** [comment]
@joran-github Wouldn't it be possible to do something like this:

    function getDatasource(): Datasource {
       return process.env() === "test" ? TestDatasource : ProductionDatasource;
    } 

Usage:

    getDatasource().getRepository(...).extend({...});

Not cool but better to duplicate everything - if this works.(?)

Today I had to refactor one of my custom repo methods. Webstorm totally blew it because it was not clear what to refactor - since the type is missing. 

So again, I really like to know, why the class syntax was dropped. Since, until now, I only encountered negative effects of this change.

**Comment by joran-github** [comment]
@nimloth05 
I was not so confident in using an environment variable because if you run the tests without this variable set, you can destroy your production database.
However, I think there is no other way so I will do it and add an assert in "beforeAll()".

Defintely, i any contributor read us, could you please give us some clues about those 2 things:

- Why was the class declaration style dropped? It seems much more "TS like" then the other. (Which seems more JS like but JS doesn't know about type space...)

- Why is the repo bound to a datasource? A repo - as I use it - is a concept from DDD in which case it encapsulates certain aspects of my business logic. Why should this logic change depending on the database I use?

**Comment by TheUnderScorer** [comment]
I was still able to use the old Repository syntax with some changes to the code:
```typescript
import {Repository} from 'typeorm';
import {TaskModel} from './TaskModel';

// Note lack of "@EntityRepository" decorator
export class TaskRepository extends Repository<TaskModel> {
   //your repository methods
}
```

And then creating it like this:
```typescript
import {TaskRepository} from './TaskRepository';
import {TaskModel} from './TaskModel';
import {DataSource} from 'typeorm';

const connection = new DataSource({...})

 const taskRepository = new TaskRepository(
   TaskModel,
   connection.createEntityManager()
);
```

So far it seems to be working fine for me, though I'm not sure if it won't create some issues with more advanced usages.

**Comment by nimloth05** [comment]
@TheUnderScorer Cool! Does this also work inside transactions?

**Comment by TheUnderScorer** [comment]
In theory, it should 😄 . But you would have to create the repository like this:
```typescript
import {TaskRepository} from './TaskRepository';
import {TaskModel} from './TaskModel';
import {DataSource} from 'typeorm';

const connection = new DataSource({...})

connection.transaction(async transaction => {
  const repository = new TaskRepository(TaskModel, transaction, transaction.queryRunner);
  
  // Do stuff...
})
```

**Comment by ppedro1** [comment]
Since this thread is probably the most comprehensive about this issue (regarding custom repository type space), I have found that the only reasonable and easy to use method in my use case is:

```
class SomethingRepository {
    static repository = DataSource.getRepository(SomethingEntity); // can use await SomethingRepository.repository.findOne(); etc
    
    someRandomMethod () {
        return this.repository.findMany(); // Type will be SomethingEntity[];
    }
}
```

I would also very much want to know about the reasoning behind this change, and how it would be possible to implement the new changes correctly so that we don't lose type space/IDE hints.

**Comment by ankyeongeun** [comment]
typeorm.providers.js file is changed. there was getCustomRepository(entity), but now it's gone...

**Comment by nkoestinger** [comment]
I found a way on how to implement custom repositories with the new version. I answered this question on Stack Overflow. Maybe this might help someone: https://stackoverflow.com/questions/72549668/how-to-do-custom-repository-using-typeorm-mongodb-in-nestjs/72887316#72887316

**Comment by niklilland** [comment]
I am very interested in learning the why behind this changed. After digging around for a bit I haven't been able to find any kind of conversation or documentation on the goal behind this change, other than a line in the release notes stating that the old way is deprecated.

**Comment by slaviqueue** [comment]
It's strange that the old simple way for creating custom repos via inheritance was removed, and it's funny that there's nothing special is going on in `extend`. Why can't initialisation be left inside `getCustomRepository`? 

```typescript
    /**
     * Extends repository with provided functions.
     */
    extend<CustomRepository>(
        custom: CustomRepository &
            ThisType<Repository<Entity> & CustomRepository>,
    ): Repository<Entity> & CustomRepository {
        // return {
        //     ...this,
        //     ...custom
        // };
        const thisRepo = this.constructor as new (...args: any[]) => typeof this
        const { target, manager, queryRunner } = this
        const cls = new (class extends thisRepo {})(
            target,
            manager,
            queryRunner,
        )
        Object.assign(cls, custom)
        return cls as any
    }
```

**Comment by nimloth05** [comment]
Does someone know if there is an active fork of 0.2? Or what did you guys do? Did you migrate? Do you keep 0.2? In our project we see two options: keep 0.2 or use something different. Preferably a fork 0f 0.2

**Comment by niklilland** [comment]
We use NestJS, so our custom repositories are becoming custom providers without too much trouble. There is a gist someone posted in another issue that another dev is using to aid in migrating our custom repos to Nest providers, in case it's helpful:

https://github.com/nestjs/typeorm/issues/1302#issuecomment-1153148826

**Comment by alphamikle** [comment]
I fully agree with @nimloth05 and see no objective reason why switching to the new API for creating custom repositories can be justified. De-facto, Nest.js has become the modern standard for writing a Node.js backend, and in conjunction with it, the new approach brings only problems and headaches, without giving any advantages.

A huge request to the typeorm developers to return backward compatibility.

**Comment by dynamikus** [comment]
First of all, Typeorm team kudos and thank you for this great release, it has some really nice new features.

Today started working on the migrations from 0.2x to 0.3x. everything was a smooth transition till I hit the custom repositories. :(.. 

All my Orm code is distributed as npm package library where I do not have any reference to any DataSource. 
My consuming applications are responsible for providing a real db connection config and initializing the DataSource. 

Now my orm package needs to initialize the Datasource even though just the applications have the db config.  

Holding off on upgrading for now, but can't wait to use 0.3x features.

Are you guys reconsidering adding back the EntityRepository pattern, it was such a useful one.

**Comment by dingyanhe** [comment]
> I found a way on how to implement custom repositories with the new version. I answered this question on Stack Overflow. Maybe this might help someone: https://stackoverflow.com/questions/72549668/how-to-do-custom-repository-using-typeorm-mongodb-in-nestjs/72887316#72887316

https://stackoverflow.com/a/74080169/9672709

**Comment by alterthecmcdeveloper26** [comment]
> I found a way on how to implement custom repositories with the new version. I answered this question on Stack Overflow. Maybe this might help someone: https://stackoverflow.com/questions/72549668/how-to-do-custom-repository-using-typeorm-mongodb-in-nestjs/72887316#72887316

I follow this approach and it seam to not work with nest-transac, I get the error "is not a function" when calling an method from service to the customer repo!

**Comment by agustinpurita** [comment]
> > I found a way on how to implement custom repositories with the new version. I answered this question on Stack Overflow. Maybe this might help someone: https://stackoverflow.com/questions/72549668/how-to-do-custom-repository-using-typeorm-mongodb-in-nestjs/72887316#72887316
> 
> I follow this approach and it seam to not work with nest-transac, I get the error "is not a function" when calling an method from service to the customer repo!

Same for me, dataSource.createEntityManager() at super() call on repository, that's not a function at the moment of intance it. I'm stuck on this, any help?

**Comment by sentientmachin3** [comment]
I was able to use the class-like declaration with the new version using this code:
```typescript
export function getCustomRepository<T>(repo: Newable<T>) {
  return new repo() as T
}

export class Users extends Repository<User> {
  constructor() {
    super(User, getRepository(User).manager)
  }

  async getAll(): Promise<User[]> {
    return this.find()
  }

  async byId(id: string): Promise<User | null> {
    return this.findOne({ where: { id: id } })
  }

  async byUsername(username: string): Promise<User | null> {
    return this.findOne({ select: { username: true }, where: { username: username } })
  }
}
```
and in the target file
```typescript
  const users = getCustomRepository(Users)
```

**Comment by robertanton81** [comment]
After some inspiration here, I have modified one of the mentioned approaches and seems working. Does anyone see any potential issues with below solution ?


`export interface ICategoryRepository extends Repository<Category> {
  ...extra methods definitions
}`


`@Injectable()
export class CategoryRepository extends Repository<Category> implements ICategoryRepository {
  constructor(@InjectDataSource() private readonly dataSource: DataSource) {
    super(Category, dataSource.createEntityManager())
  }
  
...do your stuff  defined in ICategoryRepository
  }`
  
  then you need to add to module providers and simply use as @InjectRepository(CategoryRepository) in your service's constructor.

**Comment by ortonomy** [comment]
Anyone found a good way to:

- use custom repositories
- allow services to inject other services and call them and still maintain a transaction?

"Nest Transact" seems buggy/not able to fix issues and other options really don't seem as good. 

The nest docs suggestion to use `QueryRunner` would mean either 

a) passing queryRunner around as a parameter OR
b) doing all logic for a single service method inside one call (even if it involves side effects to another service) which seems crazy....

Ideally you'd create a transaction and then any calls to a repository/ActiveRecord inside the closure would be inside the transaction and then close automatically when the method returns

**Comment by wi-ski** [comment]
@ortonomy - We have a pattern where on every request, we instantiate an object where all Repos are 'bound' to a manager (in a transaction) and all operations reference that object throughout the lifecycle of the request.

Ultimately, we do option A in your question - but we abstract it away.

We call it "the RuntimeContext".

**Comment by ntd254** [comment]
Have the same problem

**Comment by nimloth05** [comment]
And no one cares. The issue is one year old and not a single dev has commented on the issue.

**Comment by wi-ski** [comment]
Steelman-ing the decision - the pattern moves to a function invocation (vs. a class inheritance pattern) - it might just be more ergonomic and guide developers to use the library in the way authors intend.

1. You could in theory more easily achieve dynamic groups of methods/repo functions because the class inheritance pattern is just painful.
2. Nix the need of a decorator.
3. Anything akin to those points really.

Definitely intuiting a bit here - ultimately, its a true opensource library (and a great one) - and we are still able to achieve to the class inheritance pattern previously afforded.

**Comment by SpencerIsTheKey** [comment]
There's been an update in TypeORM's Documentation for custom repositories that you can see [here](https://typeorm.io/custom-repository).

Basically, they've added a `.extend()` function to the `Repository` class that takes a set of functions to add to the repository. The intended use is for each repository to be a globally exported variable. 

```
//UserRepository.ts
export const UserRepository = dataSource.getRepository(User).extend({
    findByName(firstName: string, lastName: string) {
        return this.createQueryBuilder("user")
            .where("user.firstName = :firstName", { firstName })
            .andWhere("user.lastName = :lastName", { lastName })
            .getMany()
    },
    foo(bar: string){
        return 'foo'+bar;
    },
})
```

**Comment by nimloth05** [comment]
> There's been an update in TypeORM's Documentation for custom repositories that you can see [here](https://typeorm.io/custom-repository).
> 
> Basically, they've added a `.extend()` function to the `Repository` class that takes a set of functions to add to the repository. The intended use is for each repository to be a globally exported variable.
> 
> ```
> //UserRepository.ts
> export const UserRepository = dataSource.getRepository(User).extend({
>     findByName(firstName: string, lastName: string) {
>         return this.createQueryBuilder("user")
>             .where("user.firstName = :firstName", { firstName })
>             .andWhere("user.lastName = :lastName", { lastName })
>             .getMany()
>     },
>     foo(bar: string){
>         return 'foo'+bar;
>     },
> })
> ```

Consider the part about transactions. If you'd like to use your repositories inside a transaction, you cannot use this feature.

**Comment by IonVillarreal** [comment]
hi, does anyone have an example of TypeOrm transactions with a Custom repository? try to import same as but it doesn't work 😓

**Comment by wi-ski** [comment]
@IonVillarreal - We do this:

```ts
import {
  AbstractRepository,
  CustomRepositoryCannotInheritRepositoryError,
  CustomRepositoryNotFoundError,
  Repository,
  getMetadataArgsStorage,
} from "typeorm";

import type { EntityManager, ObjectType } from "typeorm";

export const createGetCustomRepository = <T>(manager: EntityManager) => {
  return (customRepository: ObjectType<T>) => {
    const entityRepositoryMetadataArgs = getMetadataArgsStorage().entityRepositories.find((repository) => {
      return (
        repository.target ===
        (typeof customRepository === "function" ? customRepository : (customRepository as any).constructor)
      );
    });
    if (!entityRepositoryMetadataArgs) throw new CustomRepositoryNotFoundError(customRepository);

    const entityMetadata = entityRepositoryMetadataArgs.entity
      ? manager.connection.getMetadata(entityRepositoryMetadataArgs.entity)
      : undefined;
    const entityRepositoryInstance = new (entityRepositoryMetadataArgs.target as any)(
      entityRepositoryMetadataArgs.entity,
      manager,
      manager.queryRunner
    );

    // NOTE: dynamic access to protected properties. We need this to prevent unwanted properties in those classes to be exposed,
    // however we need these properties for internal work of the class
    if (entityRepositoryInstance instanceof AbstractRepository) {
      if (!(entityRepositoryInstance as any).manager) (entityRepositoryInstance as any).manager = manager;
    }
    if (entityRepositoryInstance instanceof Repository) {
      if (!entityMetadata) throw new CustomRepositoryCannotInheritRepositoryError(customRepository);
      (entityRepositoryInstance as any).manager = manager;
      // (entityRepositoryInstance as any).metadata = entityMetadata;
    }

    return entityRepositoryInstance;
  };
};
// ...
const overrideManager = (manager: EntityManager) => {
  manager.getCustomRepository = createGetCustomRepository(manager);
  return manager;
};
```

**Comment by falyoun** [comment]
Any solution

**Comment by cidisaac** [comment]
Any new on this?

**Comment by thebongy** [comment]
Here is an almost drop in replacement for the old getCustomRepository function, based on some of the solutions above:

```typescript
function GetCustomRepo<T, K extends typeof Repository<T>>(
    entity: EntityTarget<T>, Cls: K, db: DataSource) {
    return new Cls(entity, db.getRepository(entity).manager) as InstanceType<K>;
}
```

You can define a custom repository as a class as usual, like this:

```typescript
export class UserRepository extends Repository<UserEntity> {
  readUser(userId: string) {
          return this.findOne({
              where: {
                  id: userId,
              },
          });
      }
}
```

And you can create a custom repository using the datasource object and the above function:

```typescript
const userRepository = GetCustomRepo(UserEntity, UserRepository, dataSource);
const user = userRepository.readUser("my-user-id");
```

**Comment by trevorspecht** [comment]
https://github.com/typeorm/typeorm/issues/9013#issuecomment-1600681888
> Consider the part about transactions. If you'd like to use your repositories inside a transaction, you cannot use this feature.

The documentation for creating a custom repository and using it in transactions is right here:
https://typeorm.io/custom-repository

**Comment by fmax95** [comment]
@DiOps did you find a way to manage transactions using your approach ?

**Comment by DiOps** [comment]
@fmax95 I haven't as I didn't come accross that yet.

**Comment by stouch** [comment]
> I found a way on how to implement custom repositories with the new version. I answered this question on Stack Overflow. Maybe this might help someone: https://stackoverflow.com/questions/72549668/how-to-do-custom-repository-using-typeorm-mongodb-in-nestjs/72887316#72887316

This worked for us. But, is this the official solution ?

**Comment by FrancoCorleone** [comment]
I also answered this and I think it's the cleanest solution out there:
https://stackoverflow.com/a/73239250/4653234
But the thing is... transactional support is still broken

**Comment by peterLam2** [comment]
> I also answered this and I think it's the cleanest solution out there: https://stackoverflow.com/a/73239250/4653234 But the thing is... transactional support is still broken

the custom repository methods type will not included

**Comment by FrancoCorleone** [comment]
> > I also answered this and I think it's the cleanest solution out there: https://stackoverflow.com/a/73239250/4653234 But the thing is... transactional support is still broken
> 
> the custom repository methods type will not included

What do you mean?

**Comment by FrancoCorleone** [comment]
That’s simply not true my friend. You doing something wrong. I recommend my articles on Medium about Nestjs:
https://medium.com/@jedfra6

**Comment by peterLam2** [comment]
> That’s simply not true my friend. You doing something wrong. I recommend my articles on Medium about Nestjs: https://medium.com/@jedfra6

look like i am injecting a wrong repo before, but i am solving that using other solution with TheUnderScorer advice. Thank for the articles anyway

**Comment by FrancoCorleone** [comment]
I mean good it works for you but it’s not the best one. You’re escaping DI context

**Comment by peterLam2** [comment]
i can't  figure out how to use DI with transaction so ..

**Comment by FrancoCorleone** [comment]
For that you can’t but it’s still better to use decorator pattern;)Jedrzej FrankowskiWiadomość napisana przez peterLam2 ***@***.***> w dniu 28.03.2024, o godz. 11:47:﻿
i can't  figure out how to use DI with transaction so ..

**Comment by softwareplumber** [comment]
Have never understood this bizarre compulsion amongst JS devs to roll their own inheritance mechanisms. All I want to know is 'can I use  'super' in a custom repository to invoke the vanilla method in a version I am extending? In the old way of doing things, this was clear. In the new... well, I guess I'll just have to spend the time to write a test as the code in the 'extend' method is sheerest Javascript voodoo AFAIKS. So, yes, I hereby join the years-long chorus of perplexed developers wondering why this change was made in the first place.

**Comment by nuri35** [comment]
"I'm using TypeScript too, and I was looking for a modular structure to write my own custom methods alongside TypeORM's methods. Doing it this way solved my problem.
