### ISSUE TITLE
Compilation error since v0.2.15 with TypeScript 2 (working on v0.2.14)

### ISSUE THREAD

**Issue by LoicPoullain** [typeorm/typeorm#3823]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

*Project directory*
```
node_modules/
index.ts
package.json
```

*index.ts*
```typescript
import { createConnection } from 'typeorm';

async function main() {
  await createConnection();
}
```

*package.json (version 1)*
```json
{
  "scripts": {
    "build": "tsc index.ts"
  },
  "dependencies": {
    "@types/node": "^11.11.3",
    "typeorm": "^0.2.15",
    "typescript": "^3.3.3333"
  }
}
```

*package.json (version 2)*
```json
{
  "scripts": {
    "build": "tsc index.ts"
  },
  "dependencies": {
    "@types/node": "^11.11.3",
    "typeorm": "^0.2.15",
    "typescript": "^2.9.2"
  }
}
```

Running `npm run build` works with the first version of `package.json`(TypeScript version is 3).

Running `npm run build` throws an error with the second version of `package.json` (TypeScript version is 2).

```
> @ build /Users/loicpoullain/Desktop/toto
> tsc index.ts

node_modules/typeorm/connection/Connection.d.ts:40:28 - error TS1039: Initializers are not allowed in ambient contexts.

40     readonly isConnected = false;
                              ~~~~~
```

In the [documentation](https://github.com/typeorm/typeorm#typescript-configuration), TypeORM is supposed to support version 2.3 and greater.

Installing `typeorm@0.2.14` fixes the issue.

Issue firstly reported [here](https://github.com/FoalTS/foal/issues/377) by @rick-software.

**Comment by LoicPoullain** [comment]
And thank you so much for developing and maintaining this ORM. It is excellent!

**Comment by eugenchio** [comment]
@LoicPoullain , check your TS version. The latest version requires ^3.3.3333.

**Comment by rustamwin** [comment]
@eugenchio are right, @LoicPoullain see #3779

**Comment by LoicPoullain** [comment]
Thanks for the support @eugenchio and @rustamwin. I'll update my version of TypeScript then.

Should I open a PR to specify in the docs that the expected version of TypeScript is now 3.3 or greater?

Some thoughts to improve the release process: imo minor / patch versions shouldn't introduce breaking changes (such as requiring a new version of the compiler) to ensure backward compatibility. But maybe I'm wrong here. Let me know what you think.

**Comment by rustamwin** [comment]
> Should I open a PR to specify in the docs that the expected version of TypeScript is now 3.3 or greater?

PR's are welcome!
> Some thoughts to improve the release process: imo minor / patch versions shouldn't introduce breaking changes (such as requiring a new version of the compiler) to ensure backward compatibility. But maybe I'm wrong here. Let me know what you think.

adding @pleerock

**Comment by arkyminds-santhosh** [comment]
ERROR in node_modules/typeorm/connection/Connection.d.ts(40,28): error TS1039: Initializers are not allowed in ambient contexts.

**Comment by pleerock** [comment]
@arkyminds-santhosh please read messages above > you need to upgrade your typescript compiler version

**Comment by arkyminds-santhosh** [comment]
i updated ts version but i got another error

ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.10.0 but 3.3.3333 was found instead.

**Comment by pleerock** [comment]
Please use different compiler versions for your angular and backend or upgrade your angular version. Your issue isn't related to typeorm.
