### ISSUE TITLE
TypeORM custom naming strategies fail with "TypeError: namingStrategy.tableName is not a function"

### ISSUE THREAD

**Issue by PaulMest** [typeorm/typeorm#6804]
**Issue type:**
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[X] `0.2.26`, `0.2.27` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Using a custom naming strategy worked fine until 0.2.26. It is still broken in 0.2.27. After upgrading TypeORM to 0.2.26, I receive:

```
import { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';
import { Schema } from '@golevelup/profiguration';
import { SnakeNamingStrategy } from 'typeorm-naming-strategies';
import { TypeOrmModuleOptions } from '@nestjs/typeorm';

export type DbConfig = TypeOrmModuleOptions & PostgresConnectionOptions;

export const dbConfigSchema: Schema<DbConfig> = {
  ...
  namingStrategy: new SnakeNamingStrategy(),
  ...
}
```

```[Nest] 8223   - 09/29/2020, 10:55:02 AM   [ExceptionHandler] Unable to connect to the database. Retrying (1)... +2531ms
TypeError: namingStrategy.tableName is not a function
    at EntityMetadata.build (/Users/paul/code/my-project/node_modules/typeorm/metadata/EntityMetadata.js:492:58)
    at /Users/paul/code/my-project/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:67:72
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (/Users/paul/code/my-project/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:67:14)
    at ConnectionMetadataBuilder.buildEntityMetadatas (/Users/paul/code/my-project/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:58:141)
    at Connection.buildMetadatas (/Users/paul/code/my-project/node_modules/typeorm/connection/Connection.js:515:57)
    at Connection.<anonymous> (/Users/paul/code/my-project/node_modules/typeorm/connection/Connection.js:128:30)
    at step (/Users/paul/code/my-project/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/paul/code/my-project/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/Users/paul/code/my-project/node_modules/tslib/tslib.js:112:62)
```

Related issue in popular community naming strategy:
* https://github.com/tonivj5/typeorm-naming-strategies/issues/8

I believe this may have been introduced during the `ltree` support improvement.

If I downgrade TypeORM to `0.2.22`, the naming strategy works just fine.

**Comment by dmgarland** [comment]
Can confirm this is also an issue in 0.2.25

**Comment by karimkawambwa** [comment]
I ran into this error using typeorm ^0.2.29

**Comment by KornKalle** [comment]
Can confirm this issue with typeorm ^0.2.38, MariaDB 10.4, 10.5 using SnakeNamingStrategy

**Comment by antoinejaussoin** [comment]
Same here. Any news on this?

**Comment by antoinejaussoin** [comment]
I did a little bit of digging:

I've console.logged the value of `connection.namingStrategy`, on the `EntityMetadata.ts` file ([here](https://github.com/typeorm/typeorm/blob/master/src/metadata/EntityMetadata.ts#L818)).

Turns out that the value of this field is:

```

  nestedSetColumnNames: { left: 'nsleft', right: 'nsright' },
  materializedPathColumnName: 'mpath'
}
```

Which has nothing to do with the Naming Strategy interface. So something set this property wrong, somewhere.

Hope that helps.

**Comment by dragon111333** [comment]
Tis issue still happend to me in 2023
![image](https://github.com/typeorm/typeorm/assets/65722117/cb43ddd4-ad3c-4d4a-b6eb-1a3b48c866aa)
![image](https://github.com/typeorm/typeorm/assets/65722117/0697e1e5-d683-45ea-8125-c7596463b42e)
