### ISSUE TITLE
Some column types lost length property.

### ISSUE THREAD

**Issue by Kononnable** [typeorm/typeorm#1872]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[?] `cordova`
[?] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[?] `oracle`
[x] `postgres`
[?] `sqlite`
[?] `sqljs`
[?] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Between alpha.32 and alpha.34 some column types lost functionality to have specified length.
```
@Column("tinyint",{length:1})
bool: boolean;
```
On alpha.34 and next there is an error `Error: Column bool of Entity Post does not support length property.`
I think it is connected to changes introduced in 8905709c5671c29044631f1dfebe44ceb37a2e1e and 733812c085abefa3de265dafb0b4c73b058e7bb8. Some test were modified to pass, but not sure why. I didn't see anything about dropping such features in ORM(but maybe I've missed something).

**Comment by Kononnable** [comment]
You're right. Changing length to precision generate correct table, but typescript compiler report error(output js files are correct).
`entities/table.ts(15,13): error TS2345: Argument of type '"tinyint"' is not assignable to parameter of type '(type?: any) => Function'.`

I think this is because of https://github.com/typeorm/typeorm/blob/next/src/driver/types/ColumnTypes.ts#L22 - there is no tinyint in WithPrecisionColumnType, but there is one in WithLengthColumnType. It probably should also be added to driver specyfic tables e.g. https://github.com/typeorm/typeorm/blob/next/src/driver/mysql/MysqlDriver.ts#L148 .
Not sure why driver specific withPrecisionColumnTypes is an array not a intersection type, but it may be used in runtime.

This should pop up on tests right away, but test code for few column types was removed instead of being modified.

**Comment by AlexMesser** [comment]
I deleted `length` property from MySQL numeric types because they don't have length attribute and MySQL doesn't store specified number as column length. It is just a width. As MySQL doc's says:

> MySQL supports an extension for optionally specifying the display width of integer data types in parentheses following the base keyword for the type. For example, INT(4) specifies an INT with a display width of four digits.

Based on this, I plan to add `width` property for these data types.

**Comment by AlexMesser** [comment]
`width` property introduced in `typeorm@0.2.0-alpha.44`. You can try it via `npm i typeorm@next`.
