### ISSUE TITLE
ILIKE find operator

### ISSUE THREAD

**Issue by ivanveselin** [typeorm/typeorm#4418]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Would it be a big hassle to include ILIKE find operator for case insensitive string query? I see that LIKE is implemented, ILIKE would be a nice touch

**Comment by manuhortet** [comment]
Perform case insensitive operations right now is pretty counterintuitive, this is a needed feature IMO

**Comment by wafs** [comment]
If you're using postgres, I've got a solution to have a custom operator:

```typescript
import { Connection, FindOperator, FindOperatorType } from 'typeorm';

class FindOperatorWithExtras<T> extends FindOperator<T> {
  constructor(
    type: FindOperatorType | 'ilike',
    value: FindOperator<T> | T,
    useParameter?: boolean,
    multipleParameters?: boolean,
  ) {
    // @ts-ignore
    super(type, value, useParameter, multipleParameters);
  }

  public toSql(
    connection: Connection,
    aliasPath: string,
    parameters: string[],
  ): string {
    // @ts-ignore
    if (this._type === 'ilike') {
      return `${aliasPath} ILIKE ${parameters[0]}`;
    }

    return super.toSql(connection, aliasPath, parameters);
  }
}

/**
 * Find Options Operator.
 * Example: { someField: Like("%some sting%") }
 */
export function ILike<T>(
  value: T | FindOperator<T>,
): FindOperatorWithExtras<T> {
  return new FindOperatorWithExtras('ilike', value);
}
```

I would suggest opening the `FindOperator` to be extensible by consumers via something like the strategy pattern or a class, so that we don't have to do hacky things like telling TS to ignore private variable usage.

**Comment by jacobator** [comment]
I used `Raw` operator for Postgres to achieve `ILIKE` like this:

```
import { Raw } from 'typeorm';

const name = 'hello';

const books = await this.booksRepository.find({
  where: {
    name: Raw(alias => `${alias} ILIKE '%${name}%'`),
  },
});
```

**Comment by noamgat** [comment]
> If you're using postgres, I've got a solution to have a custom operator:
> 
> ```ts
> import { Connection, FindOperator, FindOperatorType } from 'typeorm';
> 
> class FindOperatorWithExtras<T> extends FindOperator<T> {
>   constructor(
>     type: FindOperatorType | 'ilike',
>     value: FindOperator<T> | T,
>     useParameter?: boolean,
>     multipleParameters?: boolean,
>   ) {
>     // @ts-ignore
>     super(type, value, useParameter, multipleParameters);
>   }
> 
>   public toSql(
>     connection: Connection,
>     aliasPath: string,
>     parameters: string[],
>   ): string {
>     // @ts-ignore
>     if (this._type === 'ilike') {
>       return `${aliasPath} ILIKE ${parameters[0]}`;
>     }
> 
>     return super.toSql(connection, aliasPath, parameters);
>   }
> }
> 
> /**
>  * Find Options Operator.
>  * Example: { someField: Like("%some sting%") }
>  */
> export function ILike<T>(
>   value: T | FindOperator<T>,
> ): FindOperatorWithExtras<T> {
>   return new FindOperatorWithExtras('ilike', value);
> }
> ```
> 
> I would suggest opening the `FindOperator` to be extensible by consumers via something like the strategy pattern or a class, so that we don't have to do hacky things like telling TS to ignore private variable usage.

This looks great. Does it piggyback on all of the sql-injection preventive measures of TypeORM?

**Comment by wafs** [comment]
> This looks great. Does it piggyback on all of the sql-injection preventive measures of TypeORM?

@noamgat I am not sure, when I inspected the source it was using this pattern. 

I feel like it is since it's using the params array unlike the 'raw' operator which uses the value directly. 

https://github.com/typeorm/typeorm/blob/abb2dd348bdd778f3a1c4b02151521d8256e449f/src/find-options/FindOperator.ts#L87

**Comment by pleerock** [comment]
Oh, we had this feature on `next` for years... But now there is a PR, so we should have it on master too.

**Comment by joeflateau** [comment]
@pleerock could that mean we have built in ILIKE in the next release?

**Comment by pleerock** [comment]
yes, if PR will be finished and merged anytime soon.

**Comment by reverie** [comment]
> ```ts
> Raw(
> ```

Watch out for SQL injection here

**Comment by leonardofalk** [comment]
I'm also looking for this, but it should fallback for `UPPER(alias) LIKE UPPER(value)` on drivers that don't support ILIKE operator.

Also, I agree that FindOperator should be public so we have less hacky more extensible code.

**Comment by XavierJece** [comment]
> I used `Raw` operator with Postgres to achieve `ILIKE` like this:
> 
> ```ts
> import { Raw } from 'typeorm';
> 
> const name = 'hello';
> 
> const books = await this.booksRepository.find({
>   where: {
>     name: Raw(alias => `${alias} ILIKE '%${name}%'`),
>   },
> });
> ```
> 
> But there's of course SQL Injection problem that comes with this.

So he is vulnerable to SQL Injections??

**Comment by imnotjames** [comment]
This is live now.

**Comment by kendallroth** [comment]
@imnotjames Just wondering what you meant by "live," as it does not appear to be noted in `CHANGELOG` notes or any tagged releases?

It is in `master` but not released as far as I can tell: [Compare latest release to master](https://github.com/typeorm/typeorm/compare/0.2.28...master)

**Comment by leonardofalk** [comment]
@kendallroth I think the latest release isn't exactly as master, this happened before.

The problem with the current implementation it only works with PostgreSQL.

My personal take on this:

```tsx
...
case "ilike":
  if (this.connection.driver instanceof PostgresqlDriver) {
    return `${aliasPath} ILIKE ${parameters[0]}`;
  }

  return `UPPER(${aliasPath}) LIKE UPPER(${parameters[0]})`;
```

**Comment by kendallroth** [comment]
@leonardofalk That's what I was understanding as well, was just curious what "is live" meant (unless that referred to just being on `master`).

> The problem with the current implementation it only works with PostgreSQL.

👍  I use PostgresSQL anyway, but does this mean it is why it hasn't been released to `master`? Or is it simply that there hasn't been a release build since it was merged?

**Comment by imnotjames** [comment]
You're right - I thought we had done a release but we hadn't.  Apologies on that.

**Comment by imnotjames** [comment]
Also - should you want to get support for drivers / dialects that don't support `ILIKE` please feel free to open another issue.  I'm sure there's a few ways to approach that & we can test each of them. :)

**Comment by geisterfurz007** [comment]
Hey, possibly stupid question but I am a little lost between next, master and released and couldn't find anything on this in the changelog (searched for "case-insensitive", "case insensitive" and "ilike"). Since the operator suggested above doesn't work in TypeScript anymore (`Property 'toSql' does not exist on type 'FindOperator<T>'.`), I am curious to know about the current status. 

I also couldn't find a PR that contained more detail in this thread nor does this seem to be in the docs anywhere yet. Is there an ETA for this?

**Comment by wazcov** [comment]
can someone specify the version this is fixed in?

**Comment by noamgat** [comment]
> Hey, possibly stupid question but I am a little lost between next, master and released and couldn't find anything on this in the changelog (searched for "case-insensitive", "case insensitive" and "ilike"). Since the operator suggested above doesn't work in TypeScript anymore (`Property 'toSql' does not exist on type 'FindOperator<T>'.`), I am curious to know about the current status.
> 
> I also couldn't find a PR that contained more detail in this thread nor does this seem to be in the docs anywhere yet. Is there an ETA for this?

I think you can now do the following instead of using the code in this issue:

return this.userRepository.findOne({ email: new FindOperator('ilike', userEmail) });

**Comment by metelski** [comment]
[This](#issuecomment-728823002) answers @geisterfurz007 's question and fixes my issue as well.

TL;DR Custom case-insensitive like operator proposed by @wafs no longer works after updating TypeORM to 0.2.29. Please see above comment to have this fixed. Thanks @noamgat!

**Comment by geisterfurz007** [comment]
Does indeed; thanks for the mention @metelski!

**Comment by IlCallo** [comment]
Seems like MySQL string [comparisons are case-insensitive by default](https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html). For that driver the 'like' operand is fine

**Comment by renatogbp** [comment]
> return this.userRepository.findOne({ email: new FindOperator('ilike', userEmail) });

this can be further simplified as:

    return this.userRepository.findOne({ email: ILike(userEmail) });

For searching it's useful to do something like:
    
    return this.userRepository.findOne({ email: ILike(`%${query.keyword}%`) });

**Comment by adsee42** [comment]
This is a great update. But how could I use it in query builder?

I have a searchUser function searches user with given `keyword`
```
await User.createQueryBuilder("user")
      .where(
        !!keyword
          ? `(user.name ILIKE '%${keyword}%' OR user.email ILIKE '%${keyword}%'`
          : "1=1"
      )
      .andWhere(...)
      .limit(limit)
      .offset(offset)
      .getManyAndCount();
```
If there's quote `'` in the keyword, the function returns error. With `FindOperator('ilike', name)`, quotes seem to be escaped.

How can I re-write above query with `FindOperator`?

**Comment by nebkat** [comment]
Does the `ILike` function work?

**Comment by adsee42** [comment]
@nebkat 
`(user.name ILIKE '%${keyword}%' OR user.email ILIKE '%${keyword}%'` works,
but I don't know how to use it as `FindOperator('ilike', name)`. I didn't found it documented anywhere.

**Comment by nebkat** [comment]
```ts
repository.find({
    name: ILike("John%")
});
```

Just import `ILike` from `typeorm`.

**Comment by 0xC0DEBA5E** [comment]
Is it safe to use user input as input to the ILike Operator? 

Would something like this
```typescript
repository.find({
    name: ILike(`%${unsafeUserInput}%`)
});
```
be vulnerable to sql injection attacks?

**Comment by LouisMazel** [comment]
> If you're using postgres, I've got a solution to have a custom operator:
> 
> ```ts
> import { Connection, FindOperator, FindOperatorType } from 'typeorm';
> 
> class FindOperatorWithExtras<T> extends FindOperator<T> {
>   constructor(
>     type: FindOperatorType | 'ilike',
>     value: FindOperator<T> | T,
>     useParameter?: boolean,
>     multipleParameters?: boolean,
>   ) {
>     // @ts-ignore
>     super(type, value, useParameter, multipleParameters);
>   }
> 
>   public toSql(
>     connection: Connection,
>     aliasPath: string,
>     parameters: string[],
>   ): string {
>     // @ts-ignore
>     if (this._type === 'ilike') {
>       return `${aliasPath} ILIKE ${parameters[0]}`;
>     }
> 
>     return super.toSql(connection, aliasPath, parameters);
>   }
> }
> 
> /**
>  * Find Options Operator.
>  * Example: { someField: Like("%some sting%") }
>  */
> export function ILike<T>(
>   value: T | FindOperator<T>,
> ): FindOperatorWithExtras<T> {
>   return new FindOperatorWithExtras('ilike', value);
> }
> ```
> 
> I would suggest opening the `FindOperator` to be extensible by consumers via something like the strategy pattern or a class, so that we don't have to do hacky things like telling TS to ignore private variable usage.

Hi, 

This solution to create a custom operator seems to no longer work with the v0.3
In detail, the class function `toSql` is never called.

I want to create another kind of operator. Do you have any solution?
