### ISSUE TITLE
Typeorm not compiling with Typescript 3.6.2 - "Excessive stack depth"

### ISSUE THREAD

**Issue by Oscuro87** [typeorm/typeorm#4681]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

* Try to build a project containing typeorm (version 0.2.18 in my case) with the newest typescript version (I used Typescript 3.6.2)
* Get an error message looking like:
```
Error TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'.

[redacted]/api/node_modules/typeorm/repository/MongoRepository.d.ts(12,22): error TS2589: Type instantiation is excessively deep and possibly infinite.

[redacted]/api/node_modules/typeorm/repository/MongoRepository.d.ts(45,5): error TS2321: Excessive stack depth comparing types '(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>) => Promise<Entity>' and '{ (id?: string | number | Date | ObjectID, options?: FindOneOptions<Entity>): Promise<Entity>; (options?: FindOneOptions<Entity>): Promise<Entity>; (conditions?: FindConditions<Entity>, options?: FindOneOptions<...>): Promise<...>; }'.
```

**Temporary workaround**

Rollback to Typescript 3.5.3, then compiling works again.

**EDIT Sept. 16, 2019: A fix has been deployed, see https://github.com/typeorm/typeorm/issues/4681#issuecomment-531512317**

**Comment by Oscuro87** [comment]
Crap, might be dupe of #4427 ... Sorry

**Comment by dimshades** [comment]
similar here, it may work out on ts 3.5.2

**Comment by juandaco** [comment]
This was solved in the latest TypeORM version `0.2.19`. Working with typescript `3.6.3`.

**Comment by Oscuro87** [comment]
Ok Confirmed, thank you for the fix :)

**Comment by Kononnable** [comment]
Looks like issue was resolved some time ago.
