### PR TITLE
fix the Excessive stack depth comparing types `FindConditions<?>` and…

### PR DESCRIPTION
**Pull request by mophy**
Fix the this error:

`error TS2321: Excessive stack depth comparing types 'FindConditions<?>' and 'FindConditions<?>'.`

Affected TypeScript versions: >=3.2.0

The fixing is according to this link: https://github.com/microsoft/TypeScript/issues/21592#issuecomment-496723647

### CODE REVIEW

**Comment by adriankott** [comment]
I am waiting for this to be merged as well .

**Comment by dcs3spp** [comment]
Also waiting for this to be merged....

**Comment by mophy** [comment]
Current work around: (re)declare the FindConditions type as this PR suggested, where you use this type. Yes, it's annoying, but it works.

**Comment by seandearnaley** [comment]
fixed on my build using "typescript": "^3.6.3-insiders.20190909" in package.json, presume 3.6.3 is imminent
