### PR TITLE
fix: move reflect-metadata to dependencies

### PR DESCRIPTION
**Pull request by mohd-akram**
### Description of change

This fixes installing via `npm install --legacy-peer-deps` which is sometimes needed.

This was introduced in #10779 but wasn't released until a few months ago, even though it was no longer required per https://github.com/typeorm/typeorm/issues/10671#issuecomment-2026816157.

### Pull-Request Checklist

-   [x] Code is up-to-date with the `master` branch
-   [ ] This pull request links relevant issues as `Fixes #00000` N/A
-   [ ] There are new or updated unit tests validating the change N/A
-   [ ] Documentation has been updated to reflect this change N/A

## Summary by CodeRabbit

- **Chores**
  - Updated dependency management by moving "reflect-metadata" to the main dependencies section for improved consistency.

### CODE REVIEW

**Comment by alumni** [comment]
TypeORM should work without `reflect-metadata`. It is only necessary if you want to use the decorators, but you don't have to use them.

File: package.json [hunk 1]
```diff
@@ -101,6 +101,7 @@
     "dedent": "^1.6.0",
     "dotenv": "^16.4.7",
     "glob": "^10.4.5",
+    "reflect-metadata": "^0.2.2",
```
Comment (OSA413) [inline package.json:104]: Is it really needed? Can you please provide an example of package.json (or a list of dependencies) where the issue is reproduced.

**Review by OSA413 — CHANGES_REQUESTED** [review]

File: package.json (hunk 1 above)
Comment (mohd-akram) [reply package.json:104]: If you do `npm install --legacy-peer-deps typeorm` and try to import it, you will get `Error: Cannot find module 'reflect-metadata'` because of [this line](https://github.com/typeorm/typeorm/blob/5904ac3db21d928e858cd7a6e5f4448fc44256d1/src/index.ts#L3).

Comment (OSA413) [reply package.json:104]: Yes, if you are using TypeScript, you need to also install `reflect-metadata` as mentioned in the  documentation. It looks like a great opportunity to improve our docs I guess.

Please see [Installation](https://github.com/typeorm/typeorm#installation)

Comment (OSA413) [reply package.json:104]: Hold on, I might be wrong

Comment (OSA413) [reply package.json:104]: Alright, I've managed to create a repository that can reproduce the error that you described.

**Comment by OSA413** [comment]
So, here's a repository that provides an example of the problem: https://github.com/OSA413/typeorm-playground/commit/e6bda775eadf037b20712d3c22321fdb6684303d

The way it works:
1. Clone the repo and run `npm i`
2. Run `npm start`, it works and returns all entries from the database.

The way it doesn't work:
1. Clone the repo and run `npm i --legacy-peer-deps typeorm`
2. Run `npm start`, it crashes with `TSError: ⨯ Unable to compile TypeScript:
src/index.ts:12:5 - error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.`

I noticed that running `npm i --legacy-peer-deps typeorm` removes the following packages from the `package-lock.json`:
- `node_modules/@types/node`
- `node_modules/reflect-metadata`
- `node_modules/undici-types`

**Comment by OSA413** [comment]
Installing `npm i --legacy-peer-deps  https://pkg.pr.new/typeorm/typeorm@11544` brings back `reflect-metadata` in the `package-lock.json` but doesn't solve the issue with the console.

**Comment by OSA413** [comment]
@michaelbromley (and you) pointed out that the because the `reflect-metadata` is imported at the index file, it means that the package is used everywhere TypeORM is used. Meaning that `reflect-metadata` should be moved to the `dependencies`.

File: package.json (hunk 1 above)
Comment (OSA413) [reply package.json:104]: Ok, the move to the `dependencies` is valid. What about the version? Should it be as it was (`"^0.1.14 || ^0.2.0"`) or as it is?

Comment (OSA413) [reply package.json:104]: Version `0.1.14` doesn't look deprecated, maybe we should set it as `^0.1.14 || ^0.2.2`?

**Comment by OSA413** [comment]
I've managed to make `reflect-metadata` optional in this repo https://github.com/OSA413/typeorm-playground/commit/80feccd2caebc1ba446b1f0ffd436cf693e09b6c using this PR https://github.com/typeorm/typeorm/pull/11545 (though it still installs with `npm i`)

I would really discuss if either of these changes is needed. @alumni @michaelbromley what do you think?

**Comment by alumni** [comment]
> @michaelbromley (and you) pointed out that the because the `reflect-metadata` is imported at the index file, it means that the package is used everywhere TypeORM is used. Meaning that `reflect-metadata` should be moved to the `dependencies`.

I think it should not be imported by TypeORM, but the users should have to import it if they want to use class-based entities.

I'm not at a computer right now, but I'd say NestJS should require the same thing, except for them it would be a mandatory peer dependency, not an optional one.

**Comment by alumni** [comment]
Saw the PR, I'd remove the import completely.

For a long time I've been wondering how are the tests working if `reflect-metadata` is not imported in the mocha setup script 😛 I didn't expect it would be imported in the productive code 😃

**Comment by alumni** [comment]
See https://github.com/typeorm/typeorm/pull/11545#issuecomment-3001971223

**Comment by OSA413** [comment]
@mohd-akram as a temporal solution I would suggest also installing `reflect-metadata` explicitly.

**Comment by alumni** [comment]
Not temporary: you have to have to install it yourself, as the docs mention: https://typeorm.io/docs/getting-started#installation

**Comment by mohd-akram** [comment]
> @mohd-akram as a temporal solution I would suggest also installing `reflect-metadata` explicitly.

This is what I have resorted to for now. I'm not using TypeScript or decorators though, so that seems wrong/unnecessary.

> Not temporary: you have to have to install it yourself, as the docs mention: https://typeorm.io/docs/getting-started#installation

The docs seem to predate 0.2.0 which added the `reflect-metadata` import to `index.ts`. I expect very few users of TypeORM have actually installed/imported `reflect-metadata` manually, and moving it to peerDependencies was a breaking change.

File: package.json (hunk 1 above)
Comment (mohd-akram) [reply package.json:104]: The range is not needed for direct dependencies since they don't need to be shared.
