### ISSUE TITLE
String enum column creates "value.substr is not a function" exception

### ISSUE THREAD

**Issue by harm-less** [typeorm/typeorm#2142]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hey,
I was already using string enums before 0.2.5, but since this version, my setup is no longer working. This is my enum field which I didn't change after updating to 0.2.5 (it's very similar to the column setup from #2081):
```ts
@Column('enum', {
	enum: [EmployeeRole.OWNER, EmployeeRole.BARBER, EmployeeRole.PUBLISHER],
	array: true
})
@IsDefined({each: true})
@MinLength(1, {each: true})
role: EmployeeRole[];
```

However, when I run a query that involves this field, I'm getting the following exception:
```
TypeError: value.substr is not a function
 at PostgresDriver.prepareHydratedValue (src\driver\postgres\PostgresDriver.ts:442:39)
```

That line is a new addition in version 0.2.5 I noticed: [diff](https://github.com/typeorm/typeorm/compare/0.2.4...0.2.5#diff-a2a8f77fc79655011d9d2b94ebc610bdR442)

The value of `value` is `[ 'owner', 'barber' ]`, but it's treating it as a string which fails of course. So it seems like the value is already converted into an array.

Am I doing something wrong or is it a bug?

Additional information:
BD table:
```mysql
CREATE TABLE IF NOT EXISTS employees (
	id integer DEFAULT nextval('employees_id_seq'::regclass) NOT NULL PRIMARY KEY,
	barbershop_id uuid NOT NULL,
	account_id uuid NOT NULL,
	role character varying[] DEFAULT '{}'::character varying[] NOT NULL,
	created_at timestamp without time zone NOT NULL DEFAULT now(),
	updated_at timestamp without time zone NOT NULL DEFAULT now(),
	deleted_at timestamp without time zone
);
```

**Comment by pleerock** [comment]
We had a bugfix in 0.2.5. Are you able to create a failing test with reproduction of your issue based on [test I made](https://github.com/typeorm/typeorm/commit/43e52c57903fa9c86c947f3c8fc45c718ee4f2e1)?

**Comment by harm-less** [comment]
I'm not able to create a failing test as it takes me a lot of time to even understand the inner workings of Typeorm to begin with.
I did however trace the query result back to [here](https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresQueryRunner.ts#L160). The enum array is already returned over there as an actual array, so I do still think [this](https://github.com/typeorm/typeorm/compare/0.2.4...0.2.5#diff-a2a8f77fc79655011d9d2b94ebc610bdR442) condition needs to check whether or not the value is already an array or not, right?

**Comment by pleerock** [comment]
You simply need to copy-paste exist test case and replace your logic, its trivial to implement and will only take half an hour to do. Take a closer [look on my test case](https://github.com/typeorm/typeorm/commit/43e52c57903fa9c86c947f3c8fc45c718ee4f2e1), what is difference between my code and yours?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.

**Comment by engineeringstuff** [comment]
If anyone else stumbles across this problem, it's because you have a column in the database that is not an enum type, but the TypeORM decorator claims that it is an enum type.
The solution is to check that the column metadata/decorator matches the type of the column declared in the database
