### ISSUE TITLE
EntityManager.create()/.save() breaks type inference with 0.3

### ISSUE THREAD

**Issue by brandon-leapyear** [typeorm/typeorm#9070]
## Issue Description

In 0.2.39, EntityManager.create() and EntityManager.save() would correctly infer the correct type given an incomplete object. Upgrading to 0.3 now, it only infers the type for the incomplete object, without using the type hint from the passed Entity class.

This commit seems to be the breaking fix: https://github.com/typeorm/typeorm/commit/b93416d7bc25006b34a90c14c497cc7e6e57e28c

Using the definition of `DeepPartial` before this commit gets the code to typecheck, previously it doesn't.

### Expected Behavior

Should use the Entity class to determine return type, not the objects.

### Actual Behavior

The return type is narrowly determined by the input objects. e.g. for the repro steps below:

```
Property 'id' does not exist on type '{ name: string }'.
```

### Steps to Reproduce

I haven't yet tried this with a minimal repro, but this is what's happening in my codebase:

```typescript
@Entity()
class UserEntity {
  @PrimaryGeneratedColumn(...)
  id: number

  @Column(...)
  name: string
}

export const insertEntity = <T>(
  entityClass: EntityTarget<T>,
  spec: DeepPartial<T>
): Promise<T> => {
  const { manager } = getConnection()
  return manager.save(manager.create(entityClass, spec))
}

const user = await insertEntity(UserEntity, { name: 'user1' })
console.log(user.id)
```

This works in 0.2, fails in 0.3. Passes in 0.3 using the 0.2 definition of DeepPartial.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  | 
| Typescript version  | x.y.zzz  | 
| TypeORM version     | x.y.zzz  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.
